PREFIX : <http://example.org/>
prefix schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?importacion ?marca ?nombre ?numeroIdentificador
WHERE {
    ?importacion rdf:type :MarcasImportaciones ;
                schema:marca ?marca ;
                schema:nombre ?nombre ;
                schema:numero_identificador ?numeroIdentificador .
}
LIMIT 10